import { GroupInfo } from '../types';

export const MOCK_DISCOVERED_GROUPS: GroupInfo[] = [
  {
    id: 'mock-1',
    title: 'دورهمی برنامه‌نویسان ایران',
    username: 'iran_dev_community',
    link: 'https://t.me/iran_dev_community',
    membersCount: 4850,
    description: 'گروه تخصصی تبادل نظر، رفع اشکال و شبکه سازی توسعه‌دهندگان فرانت‌اند، بک‌اند و موبایل. ارسال لینک آزاد با رعایت قوانین.',
    isPublic: true,
    canSendMessages: true,
    isSupergroup: true,
    isRestricted: false,
    isScam: false,
    isFake: false,
    foundByKeyword: 'برنامه نویسی',
    discoveredAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    joined: false,
    safetyScore: 95,
    recentActivityStatus: 'فعال (بیش از ۵۰ پیام امروز)'
  },
  {
    id: 'mock-2',
    title: 'گپ متخصصین پایتون و هوش مصنوعی',
    username: 'python_ai_group_ir',
    link: 'https://t.me/python_ai_group_ir',
    membersCount: 12400,
    description: 'بحث و گفتگو درباره Python، PyTorch، TensorFlow، NLP و یادگیری ماشین. گروه عمومی پرسش و پاسخ.',
    isPublic: true,
    canSendMessages: true,
    isSupergroup: true,
    isRestricted: false,
    isScam: false,
    isFake: false,
    foundByKeyword: 'پایتون',
    discoveredAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    joined: true,
    safetyScore: 98,
    recentActivityStatus: 'بسیار فعال'
  },
  {
    id: 'mock-3',
    title: 'انجمن طراحان وب و UI/UX',
    username: 'webdesigners_persian',
    link: 'https://t.me/webdesigners_persian',
    membersCount: 3120,
    description: 'محل اشتراک‌گذاری نمونه کارها، فیگما، تایپوگرافی و اصول طراحی رابط کاربری.',
    isPublic: true,
    canSendMessages: true,
    isSupergroup: true,
    isRestricted: false,
    isScam: false,
    isFake: false,
    foundByKeyword: 'طراحی وب',
    discoveredAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    joined: false,
    safetyScore: 90,
    recentActivityStatus: 'فعال'
  },
  {
    id: 'mock-4',
    title: 'دیجیتال مارکتینگ و سئو ایران',
    username: 'seo_marketing_chat',
    link: 'https://t.me/seo_marketing_chat',
    membersCount: 8900,
    description: 'پرسش و پاسخ الگوریتم‌های گوگل، بازاریابی محتوایی و کمپین‌های تبلیغاتی. ارسال پیام عمومی بدون تایید ادمین.',
    isPublic: true,
    canSendMessages: true,
    isSupergroup: true,
    isRestricted: false,
    isScam: false,
    isFake: false,
    foundByKeyword: 'سئو',
    discoveredAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    joined: false,
    safetyScore: 92,
    recentActivityStatus: 'فعال'
  },
  {
    id: 'mock-5',
    title: 'دورهمی کسب‌وکارهای نوپا (استارتاپ)',
    username: 'iran_startups_hub',
    link: 'https://t.me/iran_startups_hub',
    membersCount: 6500,
    description: 'شبکه‌سازی بنیان‌گذاران استارتاپ‌ها، سرمایه‌گذاران فرشته و منتورهای اکوسیستم فناوری.',
    isPublic: true,
    canSendMessages: true,
    isSupergroup: true,
    isRestricted: false,
    isScam: false,
    isFake: false,
    foundByKeyword: 'استارتاپ',
    discoveredAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    joined: false,
    safetyScore: 88,
    recentActivityStatus: 'فعال'
  },
  {
    id: 'mock-6',
    title: 'کانال اطلاعیه‌های ترید (فقط خواندنی)',
    username: 'crypto_news_read_only',
    link: 'https://t.me/crypto_news_read_only',
    membersCount: 15400,
    description: 'تحلیل‌های روزانه بازار رمزارزها. توجه: این یک کانال عمومی است و امکان ارسال پیام توسط کاربران وجود ندارد.',
    isPublic: true,
    canSendMessages: false, // Cannot send messages
    isSupergroup: false,
    isRestricted: false,
    isScam: false,
    isFake: false,
    foundByKeyword: 'ارز دیجیتال',
    discoveredAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    joined: false,
    safetyScore: 75,
    recentActivityStatus: 'کانال اطلاعیه'
  }
];
